[package]
name = "zed-mcp-server-miaoduo"
version = "0.0.1"
edition = "2024"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.5.0"
serde = "1.0"
schemars = "0.9"
