id = "mcp-server-master-go"
name = "Master-Go MCP Server"
description = "Model Context Protocol Server for Master-go https://mastergo.com/"
version = "0.0.1"
schema_version = 1
authors = ["aizigao <aizigao@outlook.com>"]
repository = "https://github.com/aizigao/zed-mcp-server-master-go"

[context_servers.mcp-server-master-go]
name = "Master-go MCP Server"
